title: vilinks
description: "vilinks â€” a lightweight local go/ alternative URL shortener"
theme: null
markdown: kramdown
plugins: []
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock